global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'swarm-monitor'

scrape_configs:
  - job_name: 'cadvisor'
    consul_sd_configs:
      - server: '192.168.99.100:8500'
        services: ['cadvisor']
